name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install


      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Prefer a PAT stored in repository secret GH_PAGES_PAT but fall back to the
          # automatically provided GITHUB_TOKEN if GH_PAGES_PAT is not present.
          # Ensure you either (A) add GH_PAGES_PAT or (B) give Actions Read & write permissions
          github_token: ${{ secrets.GH_PAGES_PAT || secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
